# Use Node LTS
FROM node:20-alpine

# Set working directory
WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install --production

# Copy the built code
COPY dist ./dist
COPY scripts ./scripts  # if your start relies on any scripts
COPY tsconfig.json ./

# Expose the port
EXPOSE 3000

# Use npm start to run the app
CMD ["npm", "start"]