# Use official lightweight Nginx image
FROM nginx:alpine

# Set working directory inside container
WORKDIR /etc/nginx

# Copy nginx.conf from the same folder as Dockerfile
COPY ./nginx.conf /etc/nginx/nginx.conf

# Expose HTTP port
EXPOSE 80

# Start Nginx in the foreground
CMD ["nginx", "-g", "daemon off;"]